[package]
name = "raft-kv-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
raft-kv-core = { path = "../raft-kv-core" }
serde = { workspace = true }
bincode = { workspace = true }
crc32fast = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3.9"
