[package]
name = "raft-kv-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["sync", "time", "macros"] }
async-trait = { workspace = true }
bincode = { workspace = true }

[dev-dependencies]
tempfile = "3.9"
tokio-test = "0.4"
